//! Personal to-dos, stored by the Hub on the user's own machine and synced
//! to every signed-in device through bootstrap and browser events.
use crate::agents::{AgentTask, TerminalAgentKind};
use serde::{Deserialize, Serialize};

pub const MAX_TITLE_CHARS: usize = 500;
pub const MAX_NOTES_BYTES: usize = 8 * 1024;
pub const MAX_TODOS_PER_USER: usize = 2000;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TodoStatus {
    Open,
    Done,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TodoInfo {
    /// Generated by the client, so a retried create never duplicates.
    pub id: String,
    pub title: String,
    #[serde(default)]
    pub notes: String,
    pub status: TodoStatus,
    /// Manual order among open to-dos; lower comes first.
    pub position: f64,
    /// Where the work happens, when known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub machine_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<i64>,
    /// The agent this to-do was handed to, and the terminal it runs in.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent: Option<TerminalAgentKind>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub terminal_id: Option<String>,
    /// The agent's task list as last seen. Kept after Claude clears a fully
    /// finished list, so the to-do still shows that everything was done.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress: Option<TodoProgress>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct TodoProgress {
    pub done: usize,
    pub total: usize,
    #[serde(default)]
    pub items: Vec<AgentTask>,
    pub updated_at: i64,
}

/// Trimmed title, or why it is not acceptable.
pub fn normalize_title(title: &str) -> Result<String, &'static str> {
    let title = title.trim();
    if title.is_empty() {
        return Err("The to-do needs a title");
    }
    if title.chars().count() > MAX_TITLE_CHARS {
        return Err("The title is too long");
    }
    if title.chars().any(char::is_control) {
        return Err("The title cannot contain line breaks or control characters");
    }
    Ok(title.to_string())
}

pub fn normalize_notes(notes: &str) -> Result<String, &'static str> {
    let notes = notes.replace("\r\n", "\n");
    let notes = notes.trim();
    if notes.len() > MAX_NOTES_BYTES {
        return Err("The notes are too long");
    }
    if notes
        .chars()
        .any(|c| c.is_control() && c != '\n' && c != '\t')
    {
        return Err("The notes contain control characters");
    }
    Ok(notes.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn titles_and_notes_are_trimmed_and_bounded() {
        assert_eq!(
            normalize_title("  Renew the certificate \t").unwrap(),
            "Renew the certificate"
        );
        assert!(normalize_title("   ").is_err());
        assert!(normalize_title("a\nb").is_err());
        assert!(normalize_title(&"x".repeat(MAX_TITLE_CHARS + 1)).is_err());
        assert_eq!(
            normalize_notes(" line one\r\nline two \n").unwrap(),
            "line one\nline two"
        );
        assert!(normalize_notes("a\u{1b}b").is_err());
        assert!(normalize_notes(&"x".repeat(MAX_NOTES_BYTES + 1)).is_err());
    }

    #[test]
    fn to_dos_serialize_without_empty_optionals() {
        let todo = TodoInfo {
            id: "t".into(),
            title: "Ship".into(),
            notes: String::new(),
            status: TodoStatus::Open,
            position: -1.0,
            machine_id: None,
            cwd: None,
            created_at: 1,
            updated_at: 1,
            completed_at: None,
            agent: None,
            terminal_id: None,
            progress: None,
        };
        assert_eq!(
            serde_json::to_string(&todo).unwrap(),
            r#"{"id":"t","title":"Ship","notes":"","status":"open","position":-1.0,"created_at":1,"updated_at":1}"#
        );
    }
}
