//! Continue a Claude/Codex task in the other agent.
//!
//! `GET …/relay-brief` asks the Node to read the source agent's session and
//! working tree. `POST …/relays` starts the other agent in a new terminal in
//! the same directory, with the prompt as its first message, and records
//! where the task came from. Relay ids are generated by the client, so a
//! retried request returns the terminal it already created.
use axum::{
    extract::{Path, State},
    http::StatusCode,
    response::Json,
    routing::{get, post},
    Router,
};
use offdesk_protocol::relay::{RelayAgent, RelayBrief, RelaySource, StartupPrompt, CAPABILITY};
use offdesk_protocol::TerminalInfo;
use serde::Deserialize;

use super::terminals::{auto_create_workspace_group, control_action_allowed, ensure_machine_row};
use crate::auth::AuthUser;
use crate::AppState;

type ApiError = (StatusCode, String);

const UPDATE_NODE: &str = "Update Offdesk on this machine to continue a task in another agent";

pub fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/api/machines/{machine_id}/terminals/{terminal_id}/relay-brief",
            get(relay_brief),
        )
        .route("/api/machines/{machine_id}/relays", post(create_relay))
}

#[derive(Deserialize)]
struct CreateRelayRequest {
    id: String,
    #[serde(default)]
    device_id: Option<String>,
    source_terminal_id: String,
    target_agent: RelayAgent,
    prompt: String,
    #[serde(default = "default_cols")]
    cols: u16,
    #[serde(default = "default_rows")]
    rows: u16,
}

fn default_cols() -> u16 {
    120
}

fn default_rows() -> u16 {
    40
}

fn db_error(error: impl std::fmt::Display) -> ApiError {
    tracing::error!("relay database error: {error}");
    (
        StatusCode::INTERNAL_SERVER_ERROR,
        "Could not save the relay".to_string(),
    )
}

async fn require_access(state: &AppState, user_id: &str, machine_id: &str) -> Result<(), ApiError> {
    if !state
        .manager
        .user_can_access_machine(user_id, machine_id)
        .await
    {
        return Err((StatusCode::NOT_FOUND, "Machine not found".to_string()));
    }
    Ok(())
}

async fn relay_brief(
    State(state): State<AppState>,
    auth_user: AuthUser,
    Path((machine_id, terminal_id)): Path<(String, String)>,
) -> Result<Json<RelayBrief>, ApiError> {
    require_access(&state, &auth_user.user_id, &machine_id).await?;
    if state
        .manager
        .terminal_for_user(&auth_user.user_id, &machine_id, &terminal_id)
        .await
        .is_none()
    {
        return Err((StatusCode::NOT_FOUND, "Terminal not found".to_string()));
    }
    if !state
        .manager
        .machine_supports(&machine_id, CAPABILITY)
        .await
    {
        return Err((StatusCode::CONFLICT, UPDATE_NODE.to_string()));
    }
    match state
        .manager
        .request_relay_brief(&machine_id, &terminal_id)
        .await
    {
        Ok(Ok(brief)) => Ok(Json(brief)),
        Ok(Err(message)) => Err((StatusCode::CONFLICT, message)),
        Err(message) => Err((StatusCode::SERVICE_UNAVAILABLE, message)),
    }
}

async fn create_relay(
    State(state): State<AppState>,
    auth_user: AuthUser,
    Path(machine_id): Path<String>,
    Json(req): Json<CreateRelayRequest>,
) -> Result<Json<TerminalInfo>, ApiError> {
    let user_id = auth_user.user_id.as_str();
    require_access(&state, user_id, &machine_id).await?;
    ensure_machine_row(&state, user_id, &machine_id).await?;
    let controller = state.manager.get_controller(user_id, &machine_id);
    if !control_action_allowed(controller.as_deref(), req.device_id.as_deref()) {
        return Err((StatusCode::FORBIDDEN, "Control required".to_string()));
    }
    if uuid::Uuid::parse_str(&req.id).is_err() {
        return Err((StatusCode::BAD_REQUEST, "Invalid relay id".to_string()));
    }
    let prompt = StartupPrompt::normalized(req.target_agent, &req.prompt)
        .map_err(|message| (StatusCode::BAD_REQUEST, message.to_string()))?;

    // A retry after a lost response must not start a second agent.
    let existing = {
        let conn = state.db.get().map_err(db_error)?;
        crate::db::terminal_sessions::find_by_relay_id(&conn, &machine_id, &req.id)
            .map_err(db_error)?
    };
    if let Some((terminal_id, destroyed)) = existing {
        if !destroyed {
            if let Some(terminal) = state
                .manager
                .terminal_for_user(user_id, &machine_id, &terminal_id)
                .await
            {
                return Ok(Json(terminal));
            }
        }
        return Err((
            StatusCode::CONFLICT,
            "This relay already ran and its terminal is closed".to_string(),
        ));
    }

    let source = state
        .manager
        .terminal_for_user(user_id, &machine_id, &req.source_terminal_id)
        .await
        .ok_or_else(|| (StatusCode::NOT_FOUND, "Terminal not found".to_string()))?;
    let source_agent = source
        .agent
        .as_ref()
        .map(|agent| agent.kind)
        .unwrap_or(req.target_agent.other());
    if source_agent == req.target_agent {
        return Err((
            StatusCode::BAD_REQUEST,
            format!("This terminal already runs {}", source_agent.label()),
        ));
    }
    if !state
        .manager
        .machine_supports(&machine_id, CAPABILITY)
        .await
    {
        return Err((StatusCode::CONFLICT, UPDATE_NODE.to_string()));
    }

    let terminal = state
        .manager
        .create_terminal(
            &machine_id,
            &source.cwd,
            req.cols,
            req.rows,
            None,
            Some(prompt),
        )
        .await
        .map_err(|message| (StatusCode::SERVICE_UNAVAILABLE, message))?;
    let relay_source = RelaySource {
        relay_id: req.id.clone(),
        terminal_id: source.id.clone(),
        agent: source_agent,
    };
    state
        .manager
        .set_relay_source(&machine_id, &terminal.id, relay_source.clone())
        .await;
    // The relayed agent gets its own tab, named after the directory, so the
    // source keeps its layout and the two can be switched between.
    let group_id = auto_create_workspace_group(&state, user_id, &machine_id, &terminal.cwd).await?;
    let terminal = state
        .manager
        .set_terminal_workspace_group(user_id, &machine_id, &terminal.id, Some(group_id))
        .await
        .map_err(|message| (StatusCode::INTERNAL_SERVER_ERROR, message))?;
    {
        let conn = state.db.get().map_err(db_error)?;
        crate::db::terminal_sessions::set_relay_source(&conn, &terminal.id, &relay_source)
            .map_err(db_error)?;
    }
    Ok(Json(terminal))
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use axum::{
        body::{to_bytes, Body},
        http::{header, Method, Request, StatusCode},
    };
    use offdesk_protocol::relay::{RelayAgent, TerminalAgent};
    use offdesk_protocol::{HubToMachine, MachineInfo, MachineToHub, TerminalInfo};
    use r2d2::Pool;
    use r2d2_sqlite::SqliteConnectionManager;
    use serde_json::{json, Value};
    use tokio::sync::mpsc::Receiver;
    use tower::ServiceExt;

    use crate::{
        attach_router::HubRouter, auth::sign_jwt, machine_manager::MachineManager, AppState,
    };

    const RELAY_ID: &str = "44444444-4444-4444-8444-444444444444";

    fn test_state() -> AppState {
        let pool = Pool::builder()
            .max_size(1)
            .build(SqliteConnectionManager::memory())
            .unwrap();
        let conn = pool.get().unwrap();
        crate::db::init_db(&conn).unwrap();
        crate::db::users::create_user(&conn, "user-a", "test", "user-a", "User A", None, "admin")
            .unwrap();
        crate::db::machines::ensure_machine_for_user(
            &conn,
            "machine-a",
            "user-a",
            "Machine A",
            Some("linux"),
            Some("/tmp"),
        )
        .unwrap();
        drop(conn);
        AppState {
            manager: Arc::new(MachineManager::new(pool.clone())),
            router: Arc::new(HubRouter::new()),
            web_previews: Arc::new(crate::web_preview::registry::Registry::default()),
            db: pool,
            jwt_secret: "test-secret".to_string(),
            base_url: "http://localhost:4317".to_string(),
            dev_mode: false,
            github_client_id: None,
            github_client_secret: None,
            google_client_id: None,
            google_client_secret: None,
        }
    }

    fn source_terminal() -> TerminalInfo {
        TerminalInfo {
            id: "source".into(),
            machine_id: "machine-a".into(),
            title: "Fix enrichment".into(),
            cwd: "/work/repo".into(),
            title_source: Default::default(),
            workspace_group_id: None,
            cols: 80,
            rows: 24,
            attention: None,
            agent: None,
            relay_source: None,
            reachable: true,
        }
    }

    async fn connected(capabilities: Vec<String>) -> (AppState, Receiver<HubToMachine>) {
        let state = test_state();
        let info = MachineInfo {
            id: "machine-a".into(),
            name: "Machine A".into(),
            os: "linux".into(),
            home_dir: "/tmp".into(),
            production: false,
        };
        let (_, cmd_rx) = state
            .manager
            .register_machine_with_capabilities(info, Some("user-a".into()), capabilities)
            .await;
        state
            .manager
            .handle_machine_message(
                "machine-a",
                MachineToHub::ExistingTerminals {
                    terminals: vec![source_terminal()],
                },
            )
            .await;
        state
            .manager
            .handle_machine_message(
                "machine-a",
                MachineToHub::TerminalAgent {
                    terminal_id: "source".into(),
                    agent: Some(TerminalAgent {
                        kind: RelayAgent::Claude,
                        session_id: None,
                        usage_limit: Some("Usage limit reached".into()),
                    }),
                },
            )
            .await;
        state
            .manager
            .request_control("user-a", "machine-a", "device-a");
        (state, cmd_rx)
    }

    async fn post(state: &AppState, body: Value) -> (StatusCode, Value) {
        let token = sign_jwt("user-a", &state.jwt_secret);
        let response = super::router()
            .with_state(state.clone())
            .oneshot(
                Request::builder()
                    .method(Method::POST)
                    .uri("/api/machines/machine-a/relays")
                    .header(header::AUTHORIZATION, format!("Bearer {token}"))
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(body.to_string()))
                    .unwrap(),
            )
            .await
            .unwrap();
        let status = response.status();
        let bytes = to_bytes(response.into_body(), usize::MAX).await.unwrap();
        (
            status,
            serde_json::from_slice(&bytes).unwrap_or(Value::Null),
        )
    }

    fn relay_body() -> Value {
        json!({
            "id": RELAY_ID,
            "device_id": "device-a",
            "source_terminal_id": "source",
            "target_agent": "codex",
            "prompt": "Continue the enrichment fix.\nDon't touch the pixel code.",
        })
    }

    /// Act as the Node: answer one CreateTerminal and return what it asked.
    async fn answer_create(
        state: &AppState,
        cmd_rx: &mut Receiver<HubToMachine>,
    ) -> (
        Option<String>,
        Option<offdesk_protocol::relay::StartupPrompt>,
        String,
    ) {
        match cmd_rx.recv().await.unwrap() {
            HubToMachine::CreateTerminal {
                request_id,
                cwd,
                startup_command,
                startup_prompt,
                ..
            } => {
                state
                    .manager
                    .handle_machine_message(
                        "machine-a",
                        MachineToHub::TerminalCreated {
                            request_id,
                            terminal_id: "target".into(),
                            title: "zsh".into(),
                            cwd: cwd.clone(),
                            cols: 120,
                            rows: 40,
                        },
                    )
                    .await;
                (startup_command, startup_prompt, cwd)
            }
            other => panic!("unexpected machine command: {other:?}"),
        }
    }

    #[tokio::test]
    async fn relays_start_the_other_agent_in_the_source_directory_once() {
        let (state, mut cmd_rx) = connected(vec![offdesk_protocol::relay::CAPABILITY.into()]).await;

        let request = tokio::spawn({
            let state = state.clone();
            async move { post(&state, relay_body()).await }
        });
        let (command, prompt, cwd) = answer_create(&state, &mut cmd_rx).await;
        let (status, terminal) = request.await.unwrap();
        assert_eq!(status, StatusCode::OK, "{terminal}");
        assert_eq!(command, None, "the prompt never travels as a shell command");
        let prompt = prompt.unwrap();
        assert_eq!(prompt.agent, RelayAgent::Codex);
        assert_eq!(
            prompt.text,
            "Continue the enrichment fix.\nDon't touch the pixel code."
        );
        assert_eq!(cwd, "/work/repo");
        assert_eq!(terminal["relay_source"]["terminal_id"], "source");
        assert_eq!(terminal["relay_source"]["agent"], "claude");
        assert!(terminal["workspace_group_id"].is_string());

        // The origin is persisted for the next Hub start.
        let rows = crate::db::terminal_sessions::find_all_active(&state.db.get().unwrap()).unwrap();
        let row = rows.iter().find(|row| row.id == "target").unwrap();
        assert_eq!(row.relay_source.as_ref().unwrap().relay_id, RELAY_ID);

        // A retried request returns the same terminal without a second agent.
        let (status, again) = post(&state, relay_body()).await;
        assert_eq!(status, StatusCode::OK);
        assert_eq!(again["id"], "target");
        assert!(cmd_rx.try_recv().is_err());
    }

    #[tokio::test]
    async fn relays_need_control_a_valid_prompt_and_an_updated_node() {
        let (state, _cmd_rx) = connected(Vec::new()).await;
        let mut body = relay_body();
        body["device_id"] = json!("device-b");
        assert_eq!(post(&state, body).await.0, StatusCode::FORBIDDEN);

        let mut body = relay_body();
        body["prompt"] = json!("--yolo");
        assert_eq!(post(&state, body).await.0, StatusCode::BAD_REQUEST);

        let mut body = relay_body();
        body["target_agent"] = json!("claude");
        assert_eq!(
            post(&state, body).await.0,
            StatusCode::BAD_REQUEST,
            "same agent"
        );

        let (status, message) = post(&state, relay_body()).await;
        assert_eq!(status, StatusCode::CONFLICT, "{message}");

        let mut body = relay_body();
        body["source_terminal_id"] = json!("missing");
        assert_eq!(post(&state, body).await.0, StatusCode::NOT_FOUND);
    }
}
