import { useEffect, useRef, useState } from "react";
import * as QRCode from "qrcode";
import { Body, Button } from "./Warm.web";
import { colors } from "../lib/colors";
async function copyText(text: string) {
  try { const { writeText } = await import("@tauri-apps/plugin-clipboard-manager"); await writeText(text); }
  catch { await navigator.clipboard.writeText(text); }
}
import { listSecureDevices, revokeSecureDevice, type SecureDevice } from "../lib/api";
import { isSecureConnection, useSecureConnectionStatus } from "../lib/secureTransport";

/** Codes are generated by a local native command, never by a relay-served UI. */
export function SecurePairingPanel({ baseUrl }: { baseUrl?: string }) {
  const [pairing, setPairing] = useState<{
    pairing_uri: string; hub_url: string; expires_at: number;
    connection_check?: { identity_verified: boolean; handshake_ms: number | null; legacy_routes_hidden: boolean };
  } | null>(null);
  const requestId = useRef(0);
  const qrElement = useRef<HTMLDivElement>(null);
  const [qr, setQr] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [now, setNow] = useState(Date.now());
  useEffect(() => {
    requestId.current++; setPairing(null); setQr(""); setError(null); setBusy(false);
    return () => { requestId.current++; };
  }, [baseUrl]);
  useEffect(() => {
    if (!pairing) return;
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, [pairing]);
  useEffect(() => { if (qr) qrElement.current?.scrollIntoView({ block: "nearest" }); }, [qr]);
  const expired = pairing !== null && now >= pairing.expires_at;
  const generate = async () => {
    const id = ++requestId.current;
    setBusy(true); setError(null); setPairing(null); setQr("");
    try {
      const { invoke } = await import("@tauri-apps/api/core");
      const next = await invoke<NonNullable<typeof pairing>>("hub_pair", { baseUrl: baseUrl ?? null });
      if (id !== requestId.current) return;
      const svg = await QRCode.toString(next.pairing_uri, { type: "svg", margin: 1, color: { dark: "#2b2340", light: "#fffbf4" } });
      if (id !== requestId.current) return;
      setNow(Date.now()); setPairing(next); setQr(svg);
    } catch (cause) { if (id === requestId.current) setError(String(cause)); }
    finally { if (id === requestId.current) setBusy(false); }
  };
  return <div data-testid="secure-pairing-panel" style={{ width: "100%", display: "flex", flexDirection: "column", alignItems: "center", gap: 12, borderTop: `1px solid ${colors.line}`, paddingTop: 16 }}>
    <Body size={15}>End-to-end encrypted connection</Body>
    <Body size={13} style={{ textAlign: "center" }}>Pair in an updated offdesk App. Your App and Hub encrypt terminal content before it reaches the tunnel.</Body>
    {pairing && !expired && qr ? <>
      {pairing.connection_check?.identity_verified ? <div role="status" style={{ textAlign: "center" }}>
        <Body size={13}>Hub verified · {pairing.connection_check.handshake_ms} ms handshake from this Mac</Body>
        {!pairing.connection_check.legacy_routes_hidden ? <Body size={12}>This address may also serve ordinary web connections. Use a dedicated encrypted address for a managed tunnel.</Body> : null}
      </div> : null}
      <div ref={qrElement} aria-label="Encrypted device pairing QR code" style={{ width: 240, maxWidth: "100%", background: "#fffbf4", padding: 12, borderRadius: 12 }} dangerouslySetInnerHTML={{ __html: qr }} />
      <Body size={12}>{pairing.hub_url}</Body>
      <Body size={12}>Expires in {Math.ceil((pairing.expires_at - now) / 1000)} seconds. Keep this code private.</Body>
      <Button kind="sky" onClick={() => void copyText(pairing.pairing_uri).catch(() => setError("Could not copy the pairing link"))}>Copy pairing link</Button>
    </> : null}
    {expired ? <Body size={13}>This code has expired.</Body> : null}
    {error ? <Body size={13} style={{ color: colors.err }}><span role="alert">{error}</span></Body> : null}
    <Button kind="sky" disabled={busy} onClick={() => void generate()}>{busy ? "Checking connection…" : pairing ? "Create a new pairing code" : "Pair an encrypted device"}</Button>
  </div>;
}

export function SecureDevicesPanel() {
  const secureStatus = useSecureConnectionStatus();
  const [devices, setDevices] = useState<SecureDevice[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const refresh = () => listSecureDevices().then((next) => { setDevices(next); setLoaded(true); }).catch((cause) => setError(String(cause)));
  useEffect(() => { void refresh(); }, []);
  const revoke = async (id: string) => {
    setBusy(id); setError(null);
    try { await revokeSecureDevice(id); await refresh(); }
    catch (cause) { setError(String(cause)); }
    finally { setBusy(null); }
  };
  const current = secureStatus?.device_id;
  return <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
    {isSecureConnection() ? <Body size={14}>End-to-end encrypted · {secureStatus?.endpoint.hub_url}</Body> : <Body size={13}>Devices paired for end-to-end encryption. Revoking a device closes its encrypted connections.</Body>}
    {loaded && devices.length === 0 ? <Body size={13}>No encrypted devices paired yet.</Body> : null}
    {devices.map((device) => <div key={device.id} style={{ display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" }}>
      <span style={{ flex: 1, fontSize: 14, overflowWrap: "anywhere" }}>{device.name}{device.id === current ? " (this device)" : ""}{device.revoked_at ? " · Revoked" : ""}</span>
      {!device.revoked_at ? <Button kind="ghost" disabled={busy !== null || device.id === current} onClick={() => void revoke(device.id)}>{busy === device.id ? "Revoking…" : "Revoke"}</Button> : null}
    </div>)}
    {current ? <Body size={12}>To revoke this device, use another paired device or the Hub's local Settings.</Body> : null}
    {error ? <Body size={13} style={{ color: colors.err }}><span role="alert">{error}</span></Body> : null}
  </div>;
}
